# errors.addしてエラーメッセージを追加した後にself.valid?をするとエラーメッセージが上書きされてしまう

valid? メソッドを呼び出すと、モデルのバリデーションが再実行されます。その結果、モデルの errors オブジェクトは再度初期化され、事前に errors.add で追加したエラーメッセージがクリアされてしまいます。

エラーメッセージを追加したい場合は、以下のような手順を考えると良いでしょう：

まず valid? または save などでバリデーションを実行します。
その後、必要なエラーメッセージを errors.add で追加します。
例：

```ruby
def some_method
  if self.valid?
    # 何らかの独自のチェックを行う
    if some_custom_condition
      self.errors.add(:base, "何らかのエラーメッセージ")
    end
  end
end
```

このようにすることで、モデルのデフォルトのバリデーションに加えて、独自のチェックを追加できます。
